### PR TITLE
Tiny typo fix

### PR DESCRIPTION
**Pull request by ChrisCummins**
1-char diff :)

### CODE REVIEW

**Comment by lebeaz** [comment]
Not a typo.  The init function should use the property “shares”, not the internal attribute used by the property (“_shares”).

**Comment by dabeaz** [comment]
Confirming the last comment (also by me, but on a test account—oops ;-).

**Comment by ChrisCummins** [comment]
My bad, I missed the setter. Sorry for wasting your time! :)

**Comment by dabeaz** [comment]
Not a problem!  This exact issue comes up a lot when teaching the course (question about use of shares or _shares in init).

**Pull request closed without merging**
